name: publish
on:
  release:
    types: [created]
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"
      - name: Pack
        run: dotnet pack --configuration Release --output dist /p:PackageVersion=${{ github.event.release.tag_name }}
      - name: Push
        run: dotnet nuget push ./dist/*.nupkg --source https://nuget.pkg.github.com/mattheiler/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
