name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup database
        run: docker-compose up -d

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Restore tools
        run: dotnet tool restore

      - name: Update database
        run: dotnet ef database update --project Upsertable.Tests

      - name: Test
        run: dotnet test
