name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compose
        run: docker-compose up -d

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Update
        run: dotnet ef database update --project Upsertable.SqlServer.Tests

      - name: Test
        run: dotnet test
